# basic options
title: C.elegans Whole Integration
description: Blog and code repository for the whole integration of neural connectomics, dynamics and bio-mechanics.

# build settings
markdown: kramdown
theme: minima
